- name: add post_config
  template:
    src: post_config.j2
    dest: '{{ reddit_path }}/post/post_config'
  notify: reload reddit-post


- name: create reddit-post.service
  template:
    src: reddit-post.service.j2
    dest: '/etc/systemd/system/reddit-post.service'
  notify: reload reddit-post

- name: reload reddit-post
  systemd: 
    name: reddit-post
    state: restarted
    daemon_reload: true