- name: install python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: true


- name: install post dependencies
  pip:
    state: present
    requirements: '{{ reddit_path }}/post-py/requirements.txt'
    executable: pip3
