- hosts: practice
  gather_facts: false


  pre_tasks:
    - name: clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: {{ reddit_path }}
        version: microservices_for_mc  


  roles:
    - ui
    - check_service
    
