- hosts: practice
  gather_facts: false

  pre_tasks:
    - name: clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /tmp/reddit_express42
        version: microservices_for_mc