- hosts: practice
  gather_facts: false
  become: true


  pre_tasks:
    - name: clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: '{{ reddit_path }}'
        version: microservices_for_mc


  roles:
    - role: comment_ui
      vars:
        service: ui

    - role: comment_ui
      vars:
        service: comment

    - role: post
    - role: db
    - role: check_service
    
